sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
    - php: 7.0.27
    - php: 7.1
  allow_failures:
    - php: hhvm
    
before_script: composer install

script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then phpunit --coverage-clover coverage.xml -c tests; else phpunit -c tests; fi
  
after_success:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi
