sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6

    - php: 7.0.27
    - php: 7.1
  allow_failures:
    - php: hhvm
    
script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then phpunit --coverage-clover clover.xml --bootstrap vendor/autoload.php tests; else phpunit --bootstrap vendor/autoload.php tests; fi
  
after_success:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi
